services:
  db:
    image: postgres:latest
    env_file:
      - .env
    networks:
        - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_DB=${POSTGRES_DB} 
      - ADMINER_DEFAULT_SERVER=${POSTGRES_SERVER}
      - ADMINER_DEFAULT_USERNAME=${POSTGRES_USER}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
    ports:
      - "8080:8080"
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php

  shelved:
    build:
      context: ./src
      dockerfile: dockerfile
    container_name: shelved
    env_file:
      - .env
    environment:
      - ENV=development
    develop:
      watch: 
        - path: ./src/app
          target: /src/app
          action: sync
        - path: ./src/views
          target: /src/views
          action: sync
        - path: ./src/db
          target: /src/db
          action: sync+restart
        - path: ./src/deno.json
          target: /src/deno.json
          action: sync+restart
        - path: ./src/entrypoint.sh
          action: rebuild
        - path: ./src/dockerfile
          action: rebuild
        - path: ./.env
          action: rebuild
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"


configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'db'    => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';
      ?>

networks:
  internal:
    name: internal_network
