FROM denoland/deno:alpine

WORKDIR /fullstack

COPY ./app /fullstack/app

COPY ./deno.* /fullstack/


COPY ./entrypoint.sh /fullstack/
RUN chmod +x /fullstack/entrypoint.sh

# ARG ENV=dev
#for when the complexity increases
# COPY ./run-${ENV}.sh /fullstack/run-script.sh
# RUN chmod +x /fullstack/run-script.sh

EXPOSE 3000

ENTRYPOINT ["/fullstack/entrypoint.sh"]
