# Multi-stage build for compilation
FROM denoland/deno:alpine AS builder

# Set working directory
WORKDIR /build

# Copy dependency files first
COPY deno.* ./

# Copy source code
COPY . .

# RUN deno task migrate
# RUN deno task seed

# Compile the application into a single binary
ENV DENO_DIR=/.deno_cache
RUN deno compile --no-check -A -o shelved app/main.js  \
    && chmod +x shelved 

# Install runtime dependencies
FROM denoland/deno:alpine
RUN apk add --no-cache libstdc++ libgcc
WORKDIR /app
COPY --from=builder /build/shelved /app/shelved
EXPOSE 3000
CMD ["/app/shelved"]
